name: torch-esa
channels:
  - conda-forge
  - nvidia
  - pkgs/main
  - pyg
  - pytorch
dependencies:
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - aom=3.6.0
  - attrs=24.3.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.15
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - expat=2.7.1
  - filelock=3.17.0
  - fontconfig=2.14.1
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2025.7.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - networkx=3.5
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - propcache=0.3.1
  - psutil=5.9.0
  - pycares=4.10.0
  - pycparser=2.21
  - pyg=2.6.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.11.13
  - pytorch=2.4.1
  - pytorch-cluster=1.6.3
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pyyaml=6.0.2
  - requests=2.32.5
  - scipy=1.16.0
  - setuptools=78.1.1
  - sqlite=3.50.2
  - sympy=1.14.0
  - tbb=2021.8.0
  - tk=8.6.15
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - mediapipe==0.10.14
    - tensorflow==2.15.0
    - uv==0.8.15

